In [1]:
import requests
import pandas as pd

In [2]:
# Fetch dados da api
url = "https://dados.mobilidade.rio/gps/brt"

response = requests.get(url)   
data = response.json()
df = pd.DataFrame(data['veiculos'])

In [3]:
# Dando uma olhada na estrutura e dados
df.head(15)

,codigo,placa,linha,latitude,longitude,dataHora,velocidade,id_migracao_trajeto,sentido,trajeto,hodometro,direcao,ignicao
0,901008,,22,-23.000972,-43.364938,1739767846000,0.0,,ida,22 - ALVORADA X JARDIM OCEÂNICO (PARADOR) [IDA],149790.3,,0.0
1,901011,RIV8A74,51,-23.001190,-43.364193,1739757067000,14.1,,volta,51 - T. RECREIO X T.DEODORO (PARADOR) [VOLTA],160232.1,353,1.0
2,901018,,35,-22.964850,-43.391696,1739766067000,0.0,,ida,35 - MADUREIRA X ALVORADA (PARADOR) [IDA],131265.9,64,0.0
3,901012,,51,-22.964486,-43.391595,1739767577000,0.0,,volta,51 - T. RECREIO X T.DEODORO (PARADOR) [VOLTA],133975.0,,0.0
4,901014,,46,-23.001017,-43.367612,1739766643000,0.0,,volta,46 - ALVORADA X PENHA (EXPRESSO) [VOLTA],159355.6,,0.0
5,901007,,22,-23.000924,-43.364892,1739768415000,0.0,,ida,22 - ALVORADA X JARDIM OCEÂNICO (PARADOR) [IDA],152592.2,,0.0
6,901009,,35,-22.965807,-43.391536,1739769453000,0.0,,ida,35 - MADUREIRA X ALVORADA (PARADOR) [IDA],116082.6,,0.0
7,901013,,35,-23.000941,-43.366001,1739764128000,0.0,,volta,35 - ALVORADA X MADUREIRA (PARADOR) [VOLTA],152675.6,,0.0
8,901010,RJM8G30,51,-23.000983,-43.365962,1739770637000,0.0,,volta,51 - T. RECREIO X T.DEODORO (PARADOR) [VOLTA],166681.8,,0.0
9,901015,,52,-23.000699,-43.365842,1739770248000,0.0,,volta,52 - T. ALVORADA X T. DEODORO (PARADOR) [VOLTA],164155.8,,0.0
10,901047,,35,-23.000951,-43.364939,1739770076000,0.0,,volta,35 - ALVORADA X MADUREIRA (PARADOR) [VOLTA],37054.4,,0.0
11,901017,,22,-23.000594,-43.364564,1739759179000,0.0,,ida,22 - ALVORADA X JARDIM OCEÂNICO (PARADOR) [IDA],135072.9,,0.0
12,901063,,53,-22.964613,-43.391899,1739745140000,0.0,,ida,53 - SULACAP X ALVORADA (EXPRESSO) [IDA],225025.2,,1.0
13,902319,,60,-22.848977,-43.397901,1739770362000,0.0,,ida,60 - TERMINAL DEODORO X TIG (PARADOR) [IDA],14728.7,,0.0
14,901006,RJA9F56,51,-23.000787,-43.366234,1739761320000,0.0,,volta,51 - T. RECREIO X T.DEODORO (PARADOR) [VOLTA],155010.6,,0.0

In [4]:
# Mais info do df
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 743 entries, 0 to 742
Data columns (total 13 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   codigo               743 non-null    object
 1   placa                743 non-null    object
 2   linha                743 non-null    object
 3   latitude             743 non-null    float64
 4   longitude            743 non-null    float64
 5   dataHora             743 non-null    int64
 6   velocidade           743 non-null    float64
 7   id_migracao_trajeto  743 non-null    object
 8   sentido              743 non-null    object
 9   trajeto              743 non-null    object
 10  hodometro            743 non-null    float64
 11  direcao              743 non-null    object
 12  ignicao              736 non-null    float64
dtypes: float64(5), int64(1), object(7)
memory usage: 75.6+ KB

In [5]:
# Verificando se temos nulo
df.isnull().sum()

codigo                 0
placa                  0
linha                  0
latitude               0
longitude              0
dataHora               0
velocidade             0
id_migracao_trajeto    0
sentido                0
trajeto                0
hodometro              0
direcao                0
ignicao                7
dtype: int64

In [6]:
# Retornando Lat e Long range buscando por inconsistencias
print('Latiture range:', df['latitude'].min(), "to", df['latitude'].max())
print('Longitude range:', df['longitude'].min(), 'to', df['longitude'].max())

Latiture range: -23.524419 to -22.75164
Longitude range: -46.625555 to -43.177576

In [7]:
# Retornando descricao de velocidade buscando por inconsistencias
df['velocidade'].describe()

count    743.000000
mean       2.104038
std        9.511595
min        0.000000
25%        0.000000
50%        0.000000
75%        0.000000
max       61.200000
Name: velocidade, dtype: float64

In [8]:
df['direcao'].describe()

count     743
unique    191
top
freq      441
Name: direcao, dtype: object

In [9]:
df

,codigo,placa,linha,latitude,longitude,dataHora,velocidade,id_migracao_trajeto,sentido,trajeto,hodometro,direcao,ignicao
0,901008,,22,-23.000972,-43.364938,1739767846000,0.0,,ida,22 - ALVORADA X JARDIM OCEÂNICO (PARADOR) [IDA],149790.3,,0.0
1,901011,RIV8A74,51,-23.001190,-43.364193,1739757067000,14.1,,volta,51 - T. RECREIO X T.DEODORO (PARADOR) [VOLTA],160232.1,353,1.0
2,901018,,35,-22.964850,-43.391696,1739766067000,0.0,,ida,35 - MADUREIRA X ALVORADA (PARADOR) [IDA],131265.9,64,0.0
3,901012,,51,-22.964486,-43.391595,1739767577000,0.0,,volta,51 - T. RECREIO X T.DEODORO (PARADOR) [VOLTA],133975.0,,0.0
4,901014,,46,-23.001017,-43.367612,1739766643000,0.0,,volta,46 - ALVORADA X PENHA (EXPRESSO) [VOLTA],159355.6,,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
738,902488,,17,-22.901597,-43.554227,1739771058000,0.0,,ida,17 - CAMPO GRANDE X SANTA CRUZ (PARADOR) [IDA],5707.6,183,1.0
739,902489,,17,-22.919035,-43.607378,1739771047000,0.0,,volta,17 - SANTA CRUZ X CAMPO GRANDE (PARADOR) [VOLTA],7242.5,,1.0
740,00CF000457 - A16 MAX,,0,-23.000411,-43.393521,1739415450000,56.0,,,,0.0,916,0.0
741,00B8006F63 - A8 PRO,,0,-22.919239,-43.608559,1739771064000,0.0,,,,8382.0,,1.0
742,00140007EF,,0,-22.906370,-43.177576,1738930478000,0.0,,,,0.0,,1.0